### ISSUE TITLE
KARAULOV text similarity  

### ISSUE THREAD

**Issue by Sandy4321** [jgc128/DefVectors#10]
may you share some links to read about KARAULOV similarity  
google can not find even one?

**Comment by alexanderpanchenko** [comment]
i am unsure, but it should be in this book http://it-claim.ru/Library/Books/Semantics_IT/CONTENT.HTM

**Comment by Sandy4321** [comment]
great thanks for soon answer, 
but there is no ability to content search 
by the way do you know similar code but in python?

**Comment by alexanderpanchenko** [comment]
The description is available here: http://it-claim.ru/Library/Books/Semantics_IT/gl1_2/glava1_2.htm

 Look forward the paragraph  (this is the name if the method ):

Частотно-семантический метод

**Comment by Sandy4321** [comment]
ok thanks
SPASIBO
do you know some similar projects?
